// Mock data for development

import { Problem, User, UserProgress, StudyGroup, Goal } from './types';

// Mock current user
export const mockUser: User = {
  id: 'user-1',
  name: 'Adiba Rahman',
  nameBn: 'আদিবা রহমান',
  avatar: '👩‍🎓',
  class: 'Class 12 Science',
  board: 'dhaka',
  subjects: ['physics', 'chemistry', 'math', 'biology'],
  points: 2450,
  level: 12,
  streak: 7,
};

// Mock problems
export const mockProblems: Problem[] = [
  {
    id: 'prob-1',
    title: 'Help with Newton\'s Third Law application',
    titleBn: 'নিউটনের তৃতীয় সূত্রের প্রয়োগে সাহায্য দরকার',
    description: 'I\'m confused about how to apply Newton\'s third law in collision problems. Can someone explain with an example?',
    descriptionBn: 'সংঘর্ষ সমস্যায় নিউটনের তৃতীয় সূত্র কীভাবে প্রয়োগ করতে হয় তা নিয়ে আমি বিভ্রান্ত। কেউ কি একটি উদাহরণ দিয়ে ব্যাখ্যা করতে পারবেন?',
    subject: 'physics',
    board: 'dhaka',
    urgency: 'urgent',
    tags: ['mechanics', 'newton-laws', 'collision'],
    author: {
      id: 'user-2',
      name: 'Rafiq Ahmed',
      nameBn: 'রফিক আহমেদ',
      avatar: '👨‍🎓',
      class: 'Class 11',
      board: 'dhaka',
    },
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    isSolved: false,
    status: 'answered',
    replies: [
      {
        id: 'reply-1',
        content: 'Think of it this way: when two objects collide, they exert equal and opposite forces on each other. The key is identifying the action-reaction pair.',
        author: mockUser,
        createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
        isHelpful: true,
        helpfulCount: 5,
      },
    ],
    upvotes: 12,
    saves: 8,
    viewCount: 145,
  },
  {
    id: 'prob-2',
    title: 'Organic Chemistry - Aldehyde vs Ketone',
    titleBn: 'জৈব রসায়ন - অ্যালডিহাইড বনাম কিটোন',
    description: 'What are the key differences between aldehydes and ketones? How can I identify them in reactions?',
    descriptionBn: 'অ্যালডিহাইড এবং কিটোনের মধ্যে মূল পার্থক্য কী? প্রতিক্রিয়ায় আমি কীভাবে তাদের সনাক্ত করতে পারি?',
    subject: 'chemistry',
    board: 'rajshahi',
    urgency: 'normal',
    tags: ['organic-chemistry', 'functional-groups'],
    author: {
      id: 'user-3',
      name: 'Sabrina Khan',
      nameBn: 'সাব্রিনা খান',
      avatar: '👧',
      class: 'Class 12',
      board: 'rajshahi',
    },
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000), // 5 hours ago
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    isSolved: false,
    status: 'open',
    replies: [],
    upvotes: 7,
    saves: 3,
    viewCount: 89,
  },
  {
    id: 'prob-3',
    title: 'Calculus Integration Help Needed',
    titleBn: 'ক্যালকুলাস ইন্টিগ্রেশনে সাহায্য দরকার',
    description: 'I need help solving integration by parts. Specifically with ∫x·e^x dx. Can someone walk me through the steps?',
    descriptionBn: 'আমার ইন্টিগ্রেশন বাই পার্টস সমাধানে সাহায্য দরকার। বিশেষত ∫x·e^x dx এর সাথে। কেউ কি আমাকে ধাপগুলো বুঝিয়ে দিতে পারবেন?',
    subject: 'math',
    board: 'dhaka',
    urgency: 'exam',
    tags: ['calculus', 'integration', 'by-parts'],
    author: {
      id: 'user-4',
      name: 'Tanvir Hasan',
      nameBn: 'তানভীর হাসান',
      avatar: '👦',
      class: 'HSC',
      board: 'dhaka',
    },
    createdAt: new Date(Date.now() - 30 * 60 * 1000), // 30 mins ago
    updatedAt: new Date(Date.now() - 15 * 60 * 1000),
    isSolved: true,
    status: 'solved',
    replies: [
      {
        id: 'reply-2',
        content: 'For integration by parts, use the formula: ∫u dv = uv - ∫v du. Let u = x and dv = e^x dx...',
        author: mockUser,
        createdAt: new Date(Date.now() - 15 * 60 * 1000),
        isHelpful: true,
        helpfulCount: 12,
      },
    ],
    upvotes: 23,
    saves: 15,
    viewCount: 234,
  },
  {
    id: 'prob-4',
    title: 'Cell Division - Mitosis vs Meiosis',
    titleBn: 'কোষ বিভাজন - মাইটোসিস বনাম মিয়োসিস',
    description: 'Can someone explain the main differences between mitosis and meiosis? I keep getting them confused.',
    descriptionBn: 'কেউ কি মাইটোসিস এবং মিয়োসিসের মূল পার্থক্য ব্যাখ্যা করতে পারবেন? আমি সবসময় তাদের মধ্যে গুলিয়ে ফেলি।',
    subject: 'biology',
    board: 'chittagong',
    urgency: 'normal',
    tags: ['cell-division', 'mitosis', 'meiosis'],
    author: {
      id: 'user-5',
      name: 'Nadia Islam',
      nameBn: 'নাদিয়া ইসলাম',
      avatar: '👩',
      class: 'Class 10',
      board: 'chittagong',
    },
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    isSolved: false,
    status: 'answered',
    replies: [
      {
        id: 'reply-3',
        content: 'Mitosis produces 2 identical diploid cells for growth/repair. Meiosis produces 4 unique haploid cells for reproduction.',
        author: {
          id: 'user-6',
          name: 'Dr. Rahman',
          nameBn: 'ড. রহমান',
          avatar: '👨‍🏫',
          class: 'Teacher',
          board: 'dhaka',
          subjects: ['biology'],
          points: 5000,
          level: 25,
          streak: 30,
        },
        createdAt: new Date(Date.now() - 23 * 60 * 60 * 1000),
        isHelpful: true,
        helpfulCount: 18,
      },
    ],
    upvotes: 15,
    saves: 10,
    viewCount: 178,
  },
];

// Mock user progress
export const mockProgress: UserProgress = {
  overall: {
    completion: 68,
    streak: 7,
    points: 2450,
    level: 12,
  },
  subjects: {
    physics: {
      completed: 45,
      total: 60,
      accuracy: 82,
      weakTopics: ['Electromagnetism', 'Wave Optics'],
      weakTopicsBn: ['তড়িৎচুম্বকত্ব', 'তরঙ্গ আলোকবিজ্ঞান'],
      lastPracticed: new Date(Date.now() - 2 * 60 * 60 * 1000),
    },
    chemistry: {
      completed: 38,
      total: 55,
      accuracy: 75,
      weakTopics: ['Organic Reactions', 'Equilibrium'],
      weakTopicsBn: ['জৈব বিক্রিয়া', 'সাম্যাবস্থা'],
      lastPracticed: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    },
    math: {
      completed: 52,
      total: 65,
      accuracy: 88,
      weakTopics: ['Differential Equations'],
      weakTopicsBn: ['অন্তরক সমীকরণ'],
      lastPracticed: new Date(Date.now() - 3 * 60 * 60 * 1000),
    },
    biology: {
      completed: 40,
      total: 50,
      accuracy: 90,
      weakTopics: ['Genetics'],
      weakTopicsBn: ['জিনতত্ত্ব'],
      lastPracticed: new Date(Date.now() - 5 * 60 * 60 * 1000),
    },
    english: {
      completed: 30,
      total: 40,
      accuracy: 85,
      weakTopics: ['Essay Writing'],
      weakTopicsBn: ['প্রবন্ধ লেখা'],
      lastPracticed: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    },
    bangla: {
      completed: 25,
      total: 35,
      accuracy: 92,
      weakTopics: ['Poetry Analysis'],
      weakTopicsBn: ['কবিতা বিশ্লেষণ'],
      lastPracticed: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    },
    ict: {
      completed: 20,
      total: 30,
      accuracy: 78,
      weakTopics: ['Database', 'Programming'],
      weakTopicsBn: ['ডেটাবেস', 'প্রোগ্রামিং'],
      lastPracticed: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    },
  },
  achievements: [
    {
      id: 'ach-1',
      title: '7-Day Streak',
      titleBn: '৭ দিনের ধারাবাহিকতা',
      description: 'Study for 7 consecutive days',
      descriptionBn: 'পরপর ৭ দিন অধ্যয়ন',
      icon: '🔥',
      unlockedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    },
    {
      id: 'ach-2',
      title: 'Math Master',
      titleBn: 'গণিত মাস্টার',
      description: 'Achieve 85%+ accuracy in Math',
      descriptionBn: 'গণিতে ৮৫%+ নির্ভুলতা অর্জন',
      icon: '📐',
      unlockedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    },
    {
      id: 'ach-3',
      title: 'Helper Hero',
      titleBn: 'সহায়ক নায়ক',
      description: 'Help 10 students solve their problems',
      descriptionBn: '১০ জন শিক্ষার্থীকে তাদের সমস্যা সমাধানে সাহায্য করুন',
      icon: '🦸',
      progress: 7,
      target: 10,
    },
  ],
};

// Mock study groups
export const mockStudyGroups: StudyGroup[] = [
  {
    id: 'group-1',
    name: 'HSC Physics 2025',
    nameBn: 'এইচএসসি পদার্থবিজ্ঞান ২০২৫',
    subject: 'physics',
    description: 'Preparing for HSC Physics together. Daily problem solving sessions.',
    descriptionBn: 'একসাথে এইচএসসি পদার্থবিজ্ঞানের প্রস্তুতি। প্রতিদিন সমস্যা সমাধান সেশন।',
    memberCount: 156,
    onlineCount: 23,
    nextSession: new Date(Date.now() + 2 * 60 * 60 * 1000), // 2 hours from now
    isJoined: true,
    tags: ['hsc', 'physics', 'daily-practice'],
    avatar: '⚛️',
  },
  {
    id: 'group-2',
    name: 'Organic Chemistry Warriors',
    nameBn: 'জৈব রসায়ন যোদ্ধা',
    subject: 'chemistry',
    description: 'Master organic chemistry reactions and mechanisms together.',
    descriptionBn: 'একসাথে জৈব রসায়নের বিক্রিয়া এবং পদ্ধতি আয়ত্ত করুন।',
    memberCount: 128,
    onlineCount: 18,
    nextSession: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000), // Tomorrow
    isJoined: false,
    tags: ['chemistry', 'organic', 'hsc'],
    avatar: '🧪',
  },
  {
    id: 'group-3',
    name: 'Calculus Study Circle',
    nameBn: 'ক্যালকুলাস অধ্যয়ন চক্র',
    subject: 'math',
    description: 'Weekly calculus problem solving and concept discussions.',
    descriptionBn: 'সাপ্তাহিক ক্যালকুলাস সমস্যা সমাধান এবং ধারণা আলোচনা।',
    memberCount: 203,
    onlineCount: 31,
    isJoined: true,
    tags: ['math', 'calculus', 'weekly'],
    avatar: '📊',
  },
];

// Mock today's goals
export const mockGoals: Goal[] = [
  {
    id: 'goal-1',
    title: 'Complete Physics Chapter 5',
    titleBn: 'পদার্থবিজ্ঞান অধ্যায় ৫ সম্পূর্ণ করুন',
    subject: 'physics',
    targetMinutes: 60,
    completedMinutes: 45,
    isCompleted: false,
  },
  {
    id: 'goal-2',
    title: 'Practice 10 Math Problems',
    titleBn: '১০টি গণিত সমস্যা অনুশীলন করুন',
    subject: 'math',
    targetMinutes: 45,
    completedMinutes: 45,
    isCompleted: true,
  },
  {
    id: 'goal-3',
    title: 'Review Chemistry Notes',
    titleBn: 'রসায়ন নোট পর্যালোচনা করুন',
    subject: 'chemistry',
    targetMinutes: 30,
    completedMinutes: 15,
    isCompleted: false,
  },
];
